### ISSUE TITLE
git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by sarimmehdi** [melfm/avod-ssd#10]
This is the error I get when I type the command: `git clone git@github.com:kujason/avod.git --recurse-submodules`
```
Cloning into 'avod'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Please tell me the solution. Thanks!

**Comment by pouyaramezani** [comment]
I face the same problem.
Is there any solution?

**Comment by sarimmehdi** [comment]
Please follow the instructions here: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by pouyaramezani** [comment]
my solution for the problem:
git clone https://github.com/melfm/avod-ssd.git
cd avod-ssd
git clone https://github.com/kujason/wavedata.git
