### ISSUE TITLE
How to upload Kitti results?

### ISSUE THREAD

**Issue by 408550969** [melfm/avod-ssd#5]
Hi,I have registered my account on Kitti. How do I upload the result? Do we need to upload txt documents containing test results only? How does Kitti measure the speed?
How do we distinguish between 2D and 3D object on the Kitti list?

**Comment by melfm** [comment]
Please refer to KITTI's instructions inside readme.txt file, you can also see instructions when you try to submit : "Submission instructions: For the object detection and orientation estimation as well as 3D object detection and bird's eye view benchmark, all results must be provided in the root directory of a zip file using the format described in the readme.txt"...

KITTI does not measure speed, they trust you are honest enough to provide the correct run-time speed.

**Comment by 408550969** [comment]
Thanks, would you mind share your test files? I don't know how to use the evaluate_object.cpp.

**Comment by 408550969** [comment]
Thanks for your advice. I have another question. Do I need to set 'Van' to 'Car' or ignore it when making training sets?

**Comment by eypros** [comment]
If you want to compare to other methods you should ignore them.

**Comment by hoangduyloc** [comment]
@melfm  
@408550969 
@eypros 
Sorry for bother three of you. I'm really new at submitting to the official KITTI benchmark. I want to evaluate only Bird's Eye View, when I submit this file, I got Zero scores to all, my label format for only BEV method evaluation is the image below.  Could anyone clarify for me? Thank you so much!
![image](https://user-images.githubusercontent.com/38793688/93208151-130d9100-f797-11ea-8d26-e78533df77ea.png)

**Comment by hoangduyloc** [comment]
I set the default value "The Alpha=0;  Height=0;  and Y = 0;  Trun, Occlu = -1;  2D bounding box I set to (0, 0, 0, 0) (I think my fault is here)."  Could you guys tell me where is my fault?
And if possible could anyone give me 1 line of example for only BEV evaluation, Thank you!

**Comment by wisper181** [comment]
hello, I also have doubt about this question?
I wanna test my 3D detection results on KITTI
How should I set these values?
And 2D bounding box values is necessary or not???
Can anyone help?    Thx ^_^

**Comment by gledsonmelotti** [comment]
Hello @hoangduyloc, 
Did you understand how to submit txt results to evaluate only BEV?
If so, could you provide an example?
Best regards.

**Comment by hoangduyloc** [comment]
> Hello @hoangduyloc, Did you understand how to submit txt results to evaluate only BEV? If so, could you provide an example? Best regards.

So basically 2D Object Detection Is Always Required, so the score should be at least (2D, BEV). Set Height=0, if you want to evaluate only BEV.

**Comment by gledsonmelotti** [comment]
> > Hello @hoangduyloc, Did you understand how to submit txt results to evaluate only BEV? If so, could you provide an example? Best regards.
> 
> So basically 2D Object Detection Is Always Required, so the score should be at least (2D, BEV). Set Height=0, if you want to evaluate only BEV.

Hello @hoangduyloc ,
thank you very much.

**Comment by jyunkaichen** [comment]
Hi, I tried to submit my 3D object detection results to the Kitti server , but I got an error message like this:

"Thank you for participating in our evaluation!
Loading detections...
ERROR: Couldn't read: 000000.txt
An error occured while processing your results.
Please make sure that the data in your zip archive has the right format!"

I just zip all the results into a zip file, the structure of my submission is like:

Results.zip :
 - 000000.txt
 - 000001.txt
 ...
 - 007517.txt

 Is there any file name restriction or anything that I didn't notice?

Sincerely

**Comment by jyunkaichen** [comment]
And this is the prediction format of my result. Thanks a lot.

![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)

**Comment by crjxixixi** [comment]
> And this is the prediction format of my result. Thanks a lot.
> 
> ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)

I have a same format of prediction , Do you solve the problem ?  When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)

**Comment by pengzhenD** [comment]
> > And this is the prediction format of my result. Thanks a lot.
> > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> 
> I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
Is the problem solved? I'm having the same problem

**Comment by hoangduyloc** [comment]
> > > And this is the prediction format of my result. Thanks a lot.
> > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > 
> > 
> > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > Is the problem solved? I'm having the same problem

Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files

**Comment by pengzhenD** [comment]
> > > > And this is the prediction format of my result. Thanks a lot.
> > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > 
> > > 
> > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > Is the problem solved? I'm having the same problem
> 
> Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files

Thank you very much for the tip, my problem has been solved, good luck!

**Comment by JunjieWang0528** [comment]
> > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > 
> > > > 
> > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > Is the problem solved? I'm having the same problem
> > 
> > 
> > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> 
> Thank you very much for the tip, my problem has been solved, good luck!

I also encountered this problem. Can you provide specific instructions on how to do it

**Comment by pengzhenD** [comment]
You only might zip the Txt files only, not the folder include txt files

**Comment by pengzhenD** [comment]
> > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > 
> > > > > 
> > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > Is the problem solved? I'm having the same problem
> > > 
> > > 
> > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > 
> > 
> > Thank you very much for the tip, my problem has been solved, good luck!
> 
> I also encountered this problem. Can you provide specific instructions on how to do it

You only might zip the txt files only, not the folder include txt files

**Comment by 1800710138** [comment]
> 



> > > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > > 
> > > > > > 
> > > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > > Is the problem solved? I'm having the same problem
> > > > 
> > > > 
> > > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > > 
> > > 
> > > Thank you very much for the tip, my problem has been solved, good luck!
> > 
> > 
> > I also encountered this problem. Can you provide specific instructions on how to do it
> 
> You only might zip the txt files only, not the folder include txt files

Can you provide specific contact information? qq+279237698

**Comment by IbrahimUWA** [comment]
Hello, I have trained my model on 3D  KITTI dataset for car detection. I have no idea how to generate prediction results and upload on the server. Help will be really appreciated.

Best regards
Ibrahim

**Comment by faziii0** [comment]
> > > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > > 
> > > > > > 
> > > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > > Is the problem solved? I'm having the same problem
> > > > 
> > > > 
> > > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > > 
> > > 
> > > Thank you very much for the tip, my problem has been solved, good luck!
> > 
> > 
> > I also encountered this problem. Can you provide specific instructions on how to do it
> 
> You only might zip the txt files only, not the folder include txt files

![Screenshot from 2023-12-06 09-58-22](https://github.com/melfm/avod-ssd/assets/111413133/ea9d8fe4-8aab-4687-a5c8-f93001153b10)

i have just zip the folder and directly upload one by one to kitti but still got same error do we need to upload one zip file for one class or all together. could you please help me the right way.

**Comment by pengzhenD** [comment]
You should submit the.txt file of the test results as a.zip file. Don't wrap any nested folders.

**Comment by pengzhenD** [comment]
> > > > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > > > 
> > > > > > > 
> > > > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > > > Is the problem solved? I'm having the same problem
> > > > > 
> > > > > 
> > > > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > > > 
> > > > 
> > > > Thank you very much for the tip, my problem has been solved, good luck!
> > > 
> > > 
> > > I also encountered this problem. Can you provide specific instructions on how to do it
> > 
> > 
> > You only might zip the txt files only, not the folder include txt files
> 
> ![Screenshot from 2023-12-06 09-58-22](https://private-user-images.githubusercontent.com/111413133/288253439-ea9d8fe4-8aab-4687-a5c8-f93001153b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc4NTAsIm5iZiI6MTcwMTgyNzU1MCwicGF0aCI6Ii8xMTE0MTMxMzMvMjg4MjUzNDM5LWVhOWQ4ZmU0LThhYWItNDY4Ny1hNWM4LWY5MzAwMTE1M2IxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMTUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDg4Nzc5MjM0M2IwNjRjZjQxYmY4MDdiN2ZiZDJkYjBmMTZmYmQ0OGI5MzVhZGY3YjJkNjY2MTc2YWIxMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pmwx_Mj_mqf9XPryk8zsgj_83HUnt1gXG0SkwIqjdrw)
> 
> i have just zip the folder and directly upload one by one to kitti but still got same error do we need to upload one zip file for one class or all together. could you please help me the right way.

You should submit the.txt file of the test results as a.zip file. Don't wrap any nested folders.

**Comment by pengzhenD** [comment]
> Hello, I have trained my model on 3D KITTI dataset for car detection. I have no idea how to generate prediction results and upload on the server. Help will be really appreciated.
> 
> Best regards Ibrahim

I'm really sorry for not replying to you in time. You should submit the.txt file of the test results as a.zip file. Don't wrap any nested folders.

**Comment by faziii0** [comment]
> > > > > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > > > > Is the problem solved? I'm having the same problem
> > > > > > 
> > > > > > 
> > > > > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > > > > 
> > > > > 
> > > > > Thank you very much for the tip, my problem has been solved, good luck!
> > > > 
> > > > 
> > > > I also encountered this problem. Can you provide specific instructions on how to do it
> > > 
> > > 
> > > You only might zip the txt files only, not the folder include txt files
> > 
> > 
> > ![Screenshot from 2023-12-06 09-58-22](https://private-user-images.githubusercontent.com/111413133/288253439-ea9d8fe4-8aab-4687-a5c8-f93001153b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc4NTAsIm5iZiI6MTcwMTgyNzU1MCwicGF0aCI6Ii8xMTE0MTMxMzMvMjg4MjUzNDM5LWVhOWQ4ZmU0LThhYWItNDY4Ny1hNWM4LWY5MzAwMTE1M2IxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMTUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDg4Nzc5MjM0M2IwNjRjZjQxYmY4MDdiN2ZiZDJkYjBmMTZmYmQ0OGI5MzVhZGY3YjJkNjY2MTc2YWIxMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pmwx_Mj_mqf9XPryk8zsgj_83HUnt1gXG0SkwIqjdrw)
> > i have just zip the folder and directly upload one by one to kitti but still got same error do we need to upload one zip file for one class or all together. could you please help me the right way.
> 
> You should submit the.txt file of the test results as a.zip file. Don't wrap any nested folders.

THanks for your quick response as i still did not got what are you talking about i already zip only the txt file you want me to zip the folder not the txt.file. if you could screenshot the file.
![Screenshot from 2023-12-06 12-58-53](https://github.com/melfm/avod-ssd/assets/111413133/eb2c1f7a-88b9-4300-b328-f9d04e68203f)

**Comment by pengzhenD** [comment]
> > > > > > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > > > > > Is the problem solved? I'm having the same problem
> > > > > > > 
> > > > > > > 
> > > > > > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > > > > > 
> > > > > > 
> > > > > > Thank you very much for the tip, my problem has been solved, good luck!
> > > > > 
> > > > > 
> > > > > I also encountered this problem. Can you provide specific instructions on how to do it
> > > > 
> > > > 
> > > > You only might zip the txt files only, not the folder include txt files
> > > 
> > > 
> > > ![Screenshot from 2023-12-06 09-58-22](https://private-user-images.githubusercontent.com/111413133/288253439-ea9d8fe4-8aab-4687-a5c8-f93001153b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc4NTAsIm5iZiI6MTcwMTgyNzU1MCwicGF0aCI6Ii8xMTE0MTMxMzMvMjg4MjUzNDM5LWVhOWQ4ZmU0LThhYWItNDY4Ny1hNWM4LWY5MzAwMTE1M2IxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMTUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDg4Nzc5MjM0M2IwNjRjZjQxYmY4MDdiN2ZiZDJkYjBmMTZmYmQ0OGI5MzVhZGY3YjJkNjY2MTc2YWIxMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pmwx_Mj_mqf9XPryk8zsgj_83HUnt1gXG0SkwIqjdrw)
> > > i have just zip the folder and directly upload one by one to kitti but still got same error do we need to upload one zip file for one class or all together. could you please help me the right way.
> > 
> > 
> > You should submit the.txt file of the test results as a.zip file. Don't wrap any nested folders.
> 
> THanks for your quick response as i still did not got what are you talking about i already zip only the txt file you want me to zip the folder not the txt.file. if you could screenshot the file. ![Screenshot from 2023-12-06 12-58-53](https://private-user-images.githubusercontent.com/111413133/288257335-eb2c1f7a-88b9-4300-b328-f9d04e68203f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjgzNzcsIm5iZiI6MTcwMTgyODA3NywicGF0aCI6Ii8xMTE0MTMxMzMvMjg4MjU3MzM1LWViMmMxZjdhLTg4YjktNDMwMC1iMzI4LWY5ZDA0ZTY4MjAzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGMwY2QxNjg1NTA2ZjVlMTBhZWJmZTg1NzUwYzIyNWNkODNkN2FmNThlYTY5YzAzNGIzOWJkOTk2NTk0ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kIPBOXxs1MuSZjEwnf6TXg6coo10Jy-j25EOtfXM7j4)

Just zip all the.txt files in your car folder and upload them.

**Comment by faziii0** [comment]
> > > > > > > > > > > And this is the prediction format of my result. Thanks a lot.
> > > > > > > > > > > ![image](https://user-images.githubusercontent.com/29603255/162692769-6e1dd88e-ca5b-4e0d-8adb-d8cef1f41cc5.png)
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > I have a same format of prediction , Do you solve the problem ? When I upload my results, The error is :Zip file content is either invalid or too large (>500 MB). Please try again! (accumulated size of files in zip file: 0 MB)
> > > > > > > > > > Is the problem solved? I'm having the same problem
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hi your txt format seem right, for preparing the KITTI submission format. You might zip the txt files only, not the folder include txt files
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you very much for the tip, my problem has been solved, good luck!
> > > > > > 
> > > > > > 
> > > > > > I also encountered this problem. Can you provide specific instructions on how to do it
> > > > > 
> > > > > 
> > > > > You only might zip the txt files only, not the folder include txt files
> > > > 
> > > > 
> > > > ![Screenshot from 2023-12-06 09-58-22](https://private-user-images.githubusercontent.com/111413133/288253439-ea9d8fe4-8aab-4687-a5c8-f93001153b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc4NTAsIm5iZiI6MTcwMTgyNzU1MCwicGF0aCI6Ii8xMTE0MTMxMzMvMjg4MjUzNDM5LWVhOWQ4ZmU0LThhYWItNDY4Ny1hNWM4LWY5MzAwMTE1M2IxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMTUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDg4Nzc5MjM0M2IwNjRjZjQxYmY4MDdiN2ZiZDJkYjBmMTZmYmQ0OGI5MzVhZGY3YjJkNjY2MTc2YWIxMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pmwx_Mj_mqf9XPryk8zsgj_83HUnt1gXG0SkwIqjdrw)
> > > > i have just zip the folder and directly upload one by one to kitti but still got same error do we need to upload one zip file for one class or all together. could you please help me the right way.
> > > 
> > > 
> > > You should submit the.txt file of the test results as a.zip file. Don't wrap any nested folders.
> > 
> > 
> > THanks for your quick response as i still did not got what are you talking about i already zip only the txt file you want me to zip the folder not the txt.file. if you could screenshot the file. ![Screenshot from 2023-12-06 12-58-53](https://private-user-images.githubusercontent.com/111413133/288257335-eb2c1f7a-88b9-4300-b328-f9d04e68203f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjgzNzcsIm5iZiI6MTcwMTgyODA3NywicGF0aCI6Ii8xMTE0MTMxMzMvMjg4MjU3MzM1LWViMmMxZjdhLTg4YjktNDMwMC1iMzI4LWY5ZDA0ZTY4MjAzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMjAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGMwY2QxNjg1NTA2ZjVlMTBhZWJmZTg1NzUwYzIyNWNkODNkN2FmNThlYTY5YzAzNGIzOWJkOTk2NTk0ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kIPBOXxs1MuSZjEwnf6TXg6coo10Jy-j25EOtfXM7j4)
> 
> Just zip all the.txt files in your car folder and upload them.

THanks so i need each txt file to be zipped like this.
![Screenshot from 2023-12-06 13-07-48](https://github.com/melfm/avod-ssd/assets/111413133/adcf9e18-c01b-4aed-866d-08811ffe99e4)

**Comment by pengzhenD** [comment]
> @pengzhenD
> 
> One quick question we should evaluate on the test set or val set. as it is giving me error as in valset there is no 000000.txt so it is giving me errors.

Maybe you should put all the generated.txt files in a file like res_data, then select all the.txt files in the res_data folder and compress them as name.zip and upload name.zip to kitti. Instead of dividing the detection results into different folders by category. I hope this helps you.

**Comment by faziii0** [comment]
> > @pengzhenD
> > One quick question we should evaluate on the test set or val set. as it is giving me error as in valset there is no 000000.txt so it is giving me errors.
> 
> Maybe you should put all the generated.txt files in a file like res_data, then select all the.txt files in the res_data folder and compress them as name.zip and upload name.zip to kitti. Instead of dividing the detection results into different folders by category. I hope this helps you.
Thanks for your reply
kitti VAL set does not have 000000.txt at all. Did you use testset for kitti benchmark

**Comment by faziii0** [comment]
Do we need to submit predicted results on Val or a test.
Any help would be appreciated.

Thanks!

**Comment by faziii0** [comment]
@all 

Does anyone got error like that 


Thank you for participating in our evaluation!
Loading detections...
ERROR: Couldn't read: 007481.txt
An error occured while processing your results.
Please make sure that the data in your zip archive has the right format!


All the prediction files are only 007480. where am i doing mistakes




![Screenshot from 2023-12-14 12-53-12](https://github.com/melfm/avod-ssd/assets/111413133/f8358ad4-de98-4c5a-a192-5ca314d079c9)
